name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: realtime
          POSTGRES_HOST: localhost
          POSTGRES_USER: pytest
          POSTGRES_PASSWORD: pytest_password
        ports:
        - 6012:5432

    strategy:
        matrix:
            python-version: ['3.8', '3.9']

    steps:

    - uses: actions/checkout@v1

    - name: python setup ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: install
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: run tests
      run: |
        pytest --cov=realtime tests --cov-report=xml

    - name: upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
